server:
  port: 8084

spring:
  application:
    name: appointment-service
  jpa:
    properties:
      hibernate:
        default_schema: appointment_service
  cache:
    type: redis
    cache-names: appointments
    redis:
      time-to-live: 900000  # 15 minutes

# Feign Client Configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

# Appointment Reminder Scheduler
appointment:
  reminder:
    cron: "0 0 9 * * ?"  # Every day at 9 AM
    hours-before: 24

logging:
  level:
    com.hospital.appointment: DEBUG
    feign: DEBUG
