server:
  port: 8088

spring:
  application:
    name: audit-service
  jpa:
    properties:
      hibernate:
        default_schema: audit_service

# Audit Configuration
audit:
  retention:
    days: 2555  # 7 years for HIPAA compliance
  partitioning:
    enabled: true
    interval: monthly

logging:
  level:
    com.hospital.audit: DEBUG
