server:
  port: 8081

spring:
  application:
    name: auth-service
  jpa:
    properties:
      hibernate:
        default_schema: auth_service

# JWT Configuration (RS256)
jwt:
  private-key-path: classpath:keys/private_key.pem
  public-key-path: classpath:keys/public_key.pem
  expiration: 86400000  # 24 hours in milliseconds
  refresh-expiration: 604800000  # 7 days in milliseconds

logging:
  level:
    com.hospital.auth: DEBUG
    org.springframework.security: DEBUG
