server:
  port: 8083

spring:
  application:
    name: doctor-service
  jpa:
    properties:
      hibernate:
        default_schema: doctor_service
  cache:
    type: redis
    cache-names: doctors
    redis:
      time-to-live: 3600000  # 1 hour

logging:
  level:
    com.hospital.doctor: DEBUG
