server:
  port: 8085

spring:
  application:
    name: medical-records-service
  jpa:
    properties:
      hibernate:
        default_schema: medical_records_service
  cache:
    type: redis
    cache-names: medical-records
    redis:
      time-to-live: 7200000  # 2 hours

logging:
  level:
    com.hospital.medicalrecords: DEBUG
