server:
  port: 8082

spring:
  application:
    name: patient-service
  jpa:
    properties:
      hibernate:
        default_schema: patient_service
  cache:
    type: redis
    cache-names: patients
    redis:
      time-to-live: 3600000  # 1 hour

logging:
  level:
    com.hospital.patient: DEBUG
