package com.hospital.common.enums;

public enum Disease {
    DIABETES,
    HYPERTENSION,
    ASTHMA,
    HEART_DISEASE,
    ARTHRITIS,
    CANCER,
    TUBERCULOSIS,
    COVID_19,
    PNEUMONIA,
    MALARIA,
    DENGUE,
    TYPHOID,
    KIDNEY_DISEASE,
    LIVER_DISEASE,
    THYROID_DISORDER,
    MENTAL_HEALTH_DISORDER,
    SKIN_DISEASE,
    EYE_DISEASE,
    ENT_DISORDER,
    NEUROLOGICAL_DISORDER,
    GASTROINTESTINAL_DISORDER,
    RESPIRATORY_DISORDER,
    BONE_FRACTURE,
    OTHER
}
